services:
  cu-monitor:
    env_file: .env
    environment:
      - Token=${Token}
      - DomainName=${DomainName}
      - SiteName=${SiteName}
    build: 
      context: ./monitor
      dockerfile: Dockerfile
      args:
        Token: ${Token}
        DomainName: ${DomainName}
        SiteName: ${SiteName}
    networks:
      - cu_network
    restart: unless-stopped
  
  cuagent-windows:
    env_file: .env
    environment:
      - Token=${Token}
      - DomainName=${DomainName}
      - SiteName=${SiteName}
      - AgentAuthKey=${AgentAuthKey}
      - AgentRegKey=${AgentRegKey}
    build:
      context: ./agent
      dockerfile: Dockerfile
      args:
        Token: ${Token}
        DomainName: ${DomainName}
        SiteName: ${SiteName}
    networks:
      - cu_network

networks:
  cu_network:
    external: true