services:
  cu-monitor:
    env_file: .env
    environment:
      - Token=${Token}
      - DomainName=${DomainName}
      - SiteName=${SiteName}
    build:
      context: ./monitor
      dockerfile: Dockerfile
      args:
        Token: ${Token}
        DomainName: ${DomainName}
        SiteName: ${SiteName}
    networks:
      - rt-network
    ports: 
      - ":443"
      - ":40705"
      - ":40706"
      
    hostname: ${MonitorHostName}
    restart: unless-stopped

  cuagent-windows:
    env_file: .env
    environment:
      - Token=${Token}
      - DomainName=${DomainName}
      - SiteName=${SiteName}
      - AgentAuthKey=${AgentAuthKey}
      - AgentRegKey=${AgentRegKey}
    build:
      context: ./agent
      dockerfile: Dockerfile
      args:
        Token: ${Token}
        DomainName: ${DomainName}
        SiteName: ${SiteName}
    networks:
      - rt-network
    ports: 
      - ":443"
      - ":40705"
    hostname: ${AgentHostName}`

networks:
  rt-network:
    driver: nat