name: "ControlUp-Deployment"
services:
  cu-monitor:
    container_name: "${MonitorHostName}.${DomainName}"
    env_file: .env
    environment:
      - Token=${Token}
      - DomainName=${DomainName}
      - SiteName=${SiteName}
    build:
      context: ./monitor
      dockerfile: Dockerfile
      args:
        Token: ${Token}
        DomainName: ${DomainName}
        SiteName: ${SiteName}
    networks:
      - rt-network
    ports: 
      - ":443"
      - ":40705"
      - ":40706"
    hostname: ${MonitorHostName}
    domainname: ${DomainName}
    restart: unless-stopped

  cuagent-windows:
    container_name: "${AgentHostName}.${DomainName}"
    env_file: .env
    environment:
      - Token=${Token}
      - DomainName=${DomainName}
      - SiteName=${SiteName}
      - AgentAuthKey=${AgentAuthKey}
      - AgentRegKey=${AgentRegKey}
    build:
      context: ./agent
      dockerfile: Dockerfile
      args:
        Token: ${Token}
        DomainName: ${DomainName}
        SiteName: ${SiteName}
    networks:
      - rt-network
    ports: 
      - ":443"
      - ":40705"
    depends_on:
      - cu-monitor
    hostname: ${AgentHostName}
    domainname: ${DomainName}
    restart: unless-stopped

networks:
  rt-network:
    driver: nat
    enable_ipv6: false