# escape=`

# Args used by from statements must be defined here:
ARG NanoServerRepo=windows/servercore
ARG tag=ltsc2022

FROM mcr.microsoft.com/${NanoServerRepo}:${tag}

# Switch to Administrator
USER ContainerAdministrator

# Changing to pwsh shell
SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

# Disable IPv6 on all network adapters
RUN reg add "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\Tcpip6\Parameters" /v DisabledComponents /t REG_DWORD /d 255 /f

# ARGs for the entrypoint script
ARG Token
ARG DomainName
ARG SiteName
ARG MonitorHostName

ENV Token=$Token
ENV DomainName=$DomainName
ENV SiteName=$SiteName
ENV MonitorHostName=$MonitorHostName

# Copy the install folder to the container
COPY install install
WORKDIR c:/install

EXPOSE 443
EXPOSE 40705
EXPOSE 40706
EXPOSE 135-139
EXPOSE 445
EXPOSE 49152-65535

ENTRYPOINT powershell -File c:/install/entrypoint.ps1